### ISSUE TITLE
Update arrays.php line#433 (how_often description) and 456 (downtrigger description) are not clear

### ISSUE THREAD

**Issue by mohabuhtig** [Cacti/plugin_servcheck#12]
Update arrays.php line#433 (how_often description) and 456 (downtrigger description).

I have created a pull request and modified accordingly.

https://github.com/mohabuhtig/plugin_servcheck

Kindly review and let me know if good to go.

Regards,
MSS

**Comment by TheWitness** [comment]
Yeah both pull requests are okay with me I need may need to work on the wording a little bit but yeah feel free especially that first one was pretty bad actually.

**Comment by mohabuhtig** [comment]
Hi,
What is the easiest way to create a setting tab in the configuration/settings for servcheck?

Can you guide me please.

**Comment by TheWitness** [comment]
Go to your fork, and on the page, near the branch selector, there should be a "Contribute" button.  Click it.

**Comment by xmacan** [comment]
@mohabuhtig Did you start working on "create a setting tab"? I have it on my TODO list too. I can do it in few days. let me know, please

**Comment by mohabuhtig** [comment]
I have already submitted a pull request to update the wording in 2 lines:

Update arrays.php line#433 (how_often description) and 456 (downtrigger description) are not clear #12

Awaiting review.

**Comment by mohabuhtig** [comment]
and another pull request to fix the wrong operator:

Wrong operator = instead of == in file: servcheck_process.php, line# 493

Awaiting reivew.

**Comment by xmacan** [comment]
ok, thank you!

**Comment by xmacan** [comment]
@mohabuhtig settings added 
https://github.com/Cacti/plugin_servcheck/pull/14
