### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by PCzerw** [Cacti/plugin_servcheck#17]
After install and enable not working for me.
In log I have
CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti.plugin_notification_lists' doesn't exist
and Result is Not tested yet, Curl return code is 0.

Thanks for the software.

**Comment by xmacan** [comment]
You haven't installed thold plugin?

**Comment by xmacan** [comment]
I decided remove thold dependency. I will add extra email option for your case. If thold is installed, there will be to email destination (extra email and thold notification list). It will be more universal

**Comment by xmacan** [comment]
Resolved now in main branch
