### ISSUE TITLE
/includes/arrays.php line 537 'external_id' => array(.......), it contains 'thold' instead of 'servcheck'

### ISSUE THREAD

**Issue by MSS970** [Cacti/plugin_servcheck#19]
'external_id' => array(
		'friendly_name' => __('External ID', '**_thold_**'),
		'method' => 'textbox',
		'description' => __('Enter an External ID for this test.', '**_thold_**'),
		'default' => '',
		'size' => '20',
		'max_length' => '20',
		'value' => '|arg1:external_id|',
	),

I am not sure if this is intentionally or it should be 'servcheck' instead!

**Comment by xmacan** [comment]
@MSS970 thank you for reporting. Fixed now.

**Comment by MSS970** [comment]
You are welcome 👍

**Comment by xmacan** [comment]
Status change command is the same as thold command. This function is copied from thold plugin. It runs shell script with variables listed. Script can to anything - create ticket, restart service, check service own way, ...
So yes - it can prevent false positive alerts.

**Comment by MSS970** [comment]
Can you please provide a sample script file that can be used.
Linux or Windows, it does not matter.
Much appreciated in advance.

**Comment by MSS970** [comment]
Good morning Petr,
Can you please provide a sample script file that can be used.
Linux or Windows, it does not matter.
Much appreciated in advance.

**Comment by xmacan** [comment]
It is normal shell script with few variables:
#!/bin/sh

if [ $SERVCHECK_TEST_NAME == "myname" ]
then
    echo processing myname
    if [ $SERVCHECK_RESULT != "ok" ]
     then
         // do something
    fi
else
   echo processing othername
fi

Variables:
echo SERVCHECK_TEST_NAME = $SERVCHECK_TEST_NAME >> /tmp/output.txt
echo SERVCHECK_EXTERNAL_ID = $SERVCHECK_EXTERNAL_ID >> /tmp/output.txt
echo SERVCHECK_TEST_TYPE = $SERVCHECK_TEST_TYPE >> /tmp/output.txt
echo SERVCHECK_POLLER = $SERVCHECK_POLLER >> /tmp/output.txt
echo SERVCHECK_RESULT = $SERVCHECK_RESULT >> /tmp/output.txt
echo SERVCHECK_RESULT_SEARCH = $SERVCHECK_RESULT_SEARCH >> /tmp/output.txt
echo SERVCHECK_CURL_RETURN_CODE = $SERVCHECK_CURL_RETURN_CODE >> /tmp/output.txt
echo SERVCHECK_CERTIFICATE_EXPIRATION = $SERVCHECK_CERTIFICATE_EXPIRATION >> /tmp/output.txt
