### ISSUE TITLE
URL path does not support capital letters

### ISSUE THREAD

**Issue by luisanfe** [Cacti/plugin_servcheck#3]
Hello,
If you try to use a path with capital letters, it shows you a error message:

(/plugins/servcheck/servcheck_test.php[36]:form_save(), /plugins/servcheck/servcheck_test.php[361]:get_filter_request_var(), /lib/html_utility.php[493]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())
Validation error for variable path with a value of /helpIndex.html. See backtrace below for more details.

Could we do something to be able using capital letters.

Best regards.

**Comment by xmacan** [comment]
ok, capital letters aree allowed now. Thank you for reporting

**Comment by luisanfe** [comment]
Let me suggest including the characters "?" and "="

**Comment by xmacan** [comment]
please test now
